swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{userId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Returns all transactions, grouped by month and account
      description: Returns all transactions, grouped by month and account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          description: UserId
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfull operation
          schema:
            $ref: '#/definitions/transactionModifyResponseAll'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
      
  /user/transaction/{id}:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Modify a transaction, delete, add, modify infos about a transaction
      description: modify a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of transaction
          required: true
          type: integer
          format: int64
        - in: query
          name: newInfosToPut
          description: new infos to update the transaction
          type: string
          required: true
        - in: query
          name: userId
          description: UserId
          required: true
          type: string
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionsResponse'
          
      produces:
        - application/json
        
      responses:
        '200':
          description: Reception des transactions successfull
          schema:
            $ref: '#/definitions/transactionModifyResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Visualisation of only one transaction
      description: API pour modifier une transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: userid
          in: header
          description: userId
          required: true
          type: string
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Reception des transactions successfull
          schema:
            $ref: '#/definitions/transactionModifyResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  TransactionsResponse:
    type: array
    items:
      type: object
      properties:
        id: 
          type: string
          description: Unique Id transaction
        message:
          type: string
          description: Message of transaction
        amount:
          type: number
          description: Amount of the transaction
        date:
          type: string
          description: Date of the transaction
        balance: 
          type: number
          description: Balance of the transaction
  transactionModifyResponse: 
    type: object
    properties: 
      status:
        type: string
        description: status ok 
      message: 
        type: string
        description: Message de bon fonctionnement de l'opération
  transactionModifyResponseAll:
    type: object
    properties:
      allTransactionsList:
        type: array
        items:
          type: object
          properties:
            transactionID:
              type: integer
              example: 1
          example:
            transactionId1: 1
            transactionId2: 2
            transactionId3: 3

 
  
