/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Andrey Belkin (https://sketchfab.com/belkindesign)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cards-32537e3a299d4972ac6342b8794dc6f0
title: Cards
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Card(props) {
  const { nodes, materials } = useGLTF("/card.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-7.3, 407.85, 173.26]}
            rotation={[-2.62, -0.19, 0.8]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve_CherviTuz_0.geometry}
              material={materials.CherviTuz}
            />
          </group>
          <group
            position={[114.27, -137.15, -408.97]}
            rotation={[-1.13, -0.75, -0.33]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve001_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve001_Chervi2_0.geometry}
              material={materials.Chervi2}
            />
          </group>
          <group
            position={[178.86, -223.57, -209.74]}
            rotation={[-0.44, -0.63, 0.57]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve002_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve002_Chervi3_0.geometry}
              material={materials.Chervi3}
            />
          </group>
          <group
            position={[355.3, 108.62, 385.37]}
            rotation={[-2.39, 0.3, -0.19]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve003_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve003_Chervi4_0.geometry}
              material={materials.Chervi4}
            />
          </group>
          <group
            position={[458.05, 173.21, 409.56]}
            rotation={[-2.64, -0.05, -0.89]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve004_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve004_Chervi5_0.geometry}
              material={materials.Chervi5}
            />
          </group>
          <group
            position={[560.87, 356.56, -241.49]}
            rotation={[-1.61, 0.31, -0.13]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve005_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve005_Chervi6_0.geometry}
              material={materials.Chervi6}
            />
          </group>
          <group
            position={[613.88, 285.61, -96.78]}
            rotation={[-2.3, 0.37, 0.2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve006_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve006_Chervi7_0.geometry}
              material={materials.Chervi7}
            />
          </group>
          <group
            position={[764.52, -30.74, -418.03]}
            rotation={[-2.59, 0.11, 0.7]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve007_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve007_Chervi8_0.geometry}
              material={materials.Chervi8}
            />
          </group>
          <group
            position={[820.56, 322.8, 65.22]}
            rotation={[-0.74, -0.11, -0.29]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve008_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve008_Chervi9_0.geometry}
              material={materials.Chervi9}
            />
          </group>
          <group
            position={[927.61, -333.38, 266.27]}
            rotation={[-0.44, -0.05, -0.37]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve009_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve009_Chervi10_0.geometry}
              material={materials.Chervi10}
            />
          </group>
          <group
            position={[1095.15, 40.19, -426.21]}
            rotation={[-1.27, 0.77, 0.51]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve010_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve010_CherviV_0.geometry}
              material={materials.CherviV}
            />
          </group>
          <group
            position={[1194.73, 119.6, 37.37]}
            rotation={[-0.71, 0.17, -0.29]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve011_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve011_CherviD_0.geometry}
              material={materials.CherviD}
            />
          </group>
          <group
            position={[1332.44, 9.94, 79.36]}
            rotation={[-1.45, -0.32, 0.71]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve012_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve012_CherviK_0.geometry}
              material={materials.CherviK}
            />
          </group>
          <group
            position={[27.31, 128.5, 507.92]}
            rotation={[-1.57, 0.2, 0.1]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve013_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve013_BubiTuz_0.geometry}
              material={materials.BubiTuz}
            />
          </group>
          <group
            position={[119.56, 305.18, 365.54]}
            rotation={[-0.74, -0.36, 0.78]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve014_Bubi2_0.geometry}
              material={materials.Bubi2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve014_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[239.94, 35.07, 502.68]}
            rotation={[-0.57, -0.69, -0.07]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve015_Bubi3001_0.geometry}
              material={materials["Bubi3.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve015_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[282.78, -382.41, -48.51]}
            rotation={[-1.96, -0.74, -0.14]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve016_Bubi4001_0.geometry}
              material={materials["Bubi4.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve016_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[413.82, 347.37, 55.33]}
            rotation={[-0.6, -0.54, 0.32]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve017_Bubi5001_0.geometry}
              material={materials["Bubi5.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve017_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[510.02, -244.53, 365.6]}
            rotation={[-2.82, -0.17, -0.64]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve018_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve018_Bubi6001_0.geometry}
              material={materials["Bubi6.001"]}
            />
          </group>
          <group
            position={[634.49, -35.65, 371.64]}
            rotation={[-1.42, -0.45, -0.29]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve019_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve019_Bubi7001_0.geometry}
              material={materials["Bubi7.001"]}
            />
          </group>
          <group
            position={[711.56, 55.52, 21.25]}
            rotation={[-2.58, -0.56, -0.42]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve020_Bubi8001_0.geometry}
              material={materials["Bubi8.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve020_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[891.56, 199.07, 239.48]}
            rotation={[-0.87, -0.4, 0.73]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve021_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve021_Bubi9001_0.geometry}
              material={materials["Bubi9.001"]}
            />
          </group>
          <group
            position={[997.25, 193.25, -114.73]}
            rotation={[-2.26, 0.04, -0.04]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve022_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve022_Bubi10001_0.geometry}
              material={materials["Bubi10.001"]}
            />
          </group>
          <group
            position={[1080.69, 326.86, 104.98]}
            rotation={[-0.79, 0.18, -0.28]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve023_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve023_BubiV001_0.geometry}
              material={materials["BubiV.001"]}
            />
          </group>
          <group
            position={[1146.01, -122.45, 329.32]}
            rotation={[-1.98, -0.2, 0.43]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve024_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve024_BubiD001_0.geometry}
              material={materials["BubiD.001"]}
            />
          </group>
          <group
            position={[1277.73, -162.54, 515.75]}
            rotation={[-2.22, 0.64, 0.06]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve025_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve025_BubiK001_0.geometry}
              material={materials["BubiK.001"]}
            />
          </group>
          <group
            position={[2.72, -263.94, 709.82]}
            rotation={[-2.65, 0.61, -0.05]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve026_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve026_KrestiTuz001_0.geometry}
              material={materials["KrestiTuz.001"]}
            />
          </group>
          <group
            position={[102.8, -426.03, 560.64]}
            rotation={[-0.42, 0.31, 0.64]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve027_Kresti2001_0.geometry}
              material={materials["Kresti2.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve027_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[248.45, -232, 694.57]}
            rotation={[-0.38, -0.27, 0.41]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve028_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve028_Kresti3001_0.geometry}
              material={materials["Kresti3.001"]}
            />
          </group>
          <group
            position={[301.91, 355.3, 728.75]}
            rotation={[-2.49, -0.04, 0.8]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve029_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve029_Kresti4001_0.geometry}
              material={materials["Kresti4.001"]}
            />
          </group>
          <group
            position={[403.24, -180.11, -11.65]}
            rotation={[-1.76, -0.87, 0.3]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve030_Kresti5001_0.geometry}
              material={materials["Kresti5.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve030_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[557.14, -434.71, 354.32]}
            rotation={[-2.55, 0.38, -0.35]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve031_Kresti6001_0.geometry}
              material={materials["Kresti6.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve031_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[605.03, 110, 431.06]}
            rotation={[-2.58, -0.75, 0.11]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve032_Kresti7001_0.geometry}
              material={materials["Kresti7.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve032_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[762.51, 214.21, 67.25]}
            rotation={[-1.04, 0.3, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve033_Kresti8001_0.geometry}
              material={materials["Kresti8.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve033_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[839.11, -383.07, 730.42]}
            rotation={[-2.74, -0.26, -0.71]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve034_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve034_Kresti9001_0.geometry}
              material={materials["Kresti9.001"]}
            />
          </group>
          <group
            position={[944.48, 60.62, 24.97]}
            rotation={[-2.49, 0.15, 0.06]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve035_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve035_Kresti10001_0.geometry}
              material={materials["Kresti10.001"]}
            />
          </group>
          <group
            position={[1090.46, 310.86, 446.25]}
            rotation={[-2.58, -0.01, 0.05]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve036_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve036_KrestiV001_0.geometry}
              material={materials["KrestiV.001"]}
            />
          </group>
          <group
            position={[1222.34, -309.17, 207.3]}
            rotation={[-1.33, 0.35, 0.39]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve037_KrestiD001_0.geometry}
              material={materials["KrestiD.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve037_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[1324.27, 423.56, 248.81]}
            rotation={[-2.31, 0.23, 0.58]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve038_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve038_KrestiK001_0.geometry}
              material={materials["KrestiK.001"]}
            />
          </group>
          <group
            position={[-27.3, 22.92, 77.23]}
            rotation={[-1.52, 0.75, -0.22]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve039_PikiTuz001_0.geometry}
              material={materials["PikiTuz.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve039_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[68.49, 200.56, 761.2]}
            rotation={[-1.09, -0.83, -0.14]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve040_Piki2001_0.geometry}
              material={materials["Piki2.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve040_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[170.04, -449.02, 669.12]}
            rotation={[-2.18, -0.43, -0.52]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve041_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve041_Piki3001_0.geometry}
              material={materials["Piki3.001"]}
            />
          </group>
          <group
            position={[314.06, -115.22, 833.99]}
            rotation={[-0.98, 0.38, -0.56]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve042_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve042_Piki4001_0.geometry}
              material={materials["Piki4.001"]}
            />
          </group>
          <group
            position={[396.98, 45.91, 110.71]}
            rotation={[-0.69, -0.89, 0.01]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve043_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve043_Piki5001_0.geometry}
              material={materials["Piki5.001"]}
            />
          </group>
          <group
            position={[496.09, -435.81, 94.39]}
            rotation={[-2.21, 0.29, 0.76]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve044_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve044_Piki6001_0.geometry}
              material={materials["Piki6.001"]}
            />
          </group>
          <group
            position={[620.96, -227.42, 843.71]}
            rotation={[-2.09, -0.55, -0.4]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve045_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve045_Piki7001_0.geometry}
              material={materials["Piki7.001"]}
            />
          </group>
          <group
            position={[759.29, -244.19, 238.08]}
            rotation={[-0.32, -0.23, -0.81]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve046_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve046_Piki8001_0.geometry}
              material={materials["Piki8.001"]}
            />
          </group>
          <group
            position={[864.9, 68.98, 173.52]}
            rotation={[-1.43, -0.4, 0.28]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve047_Piki9001_0.geometry}
              material={materials["Piki9.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve047_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[950.93, 303.79, 375.38]}
            rotation={[-1.39, -0.32, 0.26]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve048_Piki10001_0.geometry}
              material={materials["Piki10.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve048_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[1069.12, -1.81, 429.86]}
            rotation={[-0.96, 0.53, -0.13]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve049_PikiV001_0.geometry}
              material={materials["PikiV.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve049_Oborot_0.geometry}
              material={materials.Oborot}
            />
          </group>
          <group
            position={[1226.4, 145.49, 341.51]}
            rotation={[-2.76, 0.04, 0.25]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve050_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve050_PikiD001_0.geometry}
              material={materials["PikiD.001"]}
            />
          </group>
          <group
            position={[1299.54, -17.43, 473.49]}
            rotation={[-1.98, 0.04, 0.58]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve051_Oborot_0.geometry}
              material={materials.Oborot}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Curve051_PikiK001_0.geometry}
              material={materials["PikiK.001"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/card.gltf");