/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sousinho (https://sketchfab.com/sousinho)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/katakana-alphabet-poster-9f169346ec1c49858033e3f872e4b7a6
title: katakana alphabet poster
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Languages(props) {
  const { nodes, materials } = useGLTF("/languages.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.Material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/languages.gltf");
