/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ryno (https://sketchfab.com/rynodaxter)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/wooden-training-dummy-3b4054d8c3814c99a2cca8332d08e6fe
title: Wooden Training Dummy
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Martial(props) {
  const { nodes, materials } = useGLTF("/martial.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[0, 93.48, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <group position={[0, -0.23, -0.55]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Stick_4_Wood_Material_0.geometry}
                material={materials.Wood_Material}
              />
            </group>
            <group
              position={[0, 0, 0.4]}
              rotation={[0, 0, -Math.PI]}
              scale={0.93}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Black_Matte_Black_Matte_0.geometry}
                material={materials.Black_Matte}
              />
            </group>
            <group position={[0, 0, -0.98]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Black_Matte_2_Black_Matte_0.geometry}
                material={materials.Black_Matte}
              />
            </group>
            <group position={[0, -0.16, 0.19]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Stick_1_Wood_Material_0.geometry}
                material={materials.Wood_Material}
              />
            </group>
            <group position={[0, 0, -0.89]} rotation={[0, 0, Math.PI / 9]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Stick_2_Wood_Material_0.geometry}
                material={materials.Wood_Material}
              />
            </group>
            <group position={[0, 0, -0.74]} rotation={[0, 0, -Math.PI / 9]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Stick_3_Wood_Material_0.geometry}
                material={materials.Wood_Material}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wooden_Training_Dummy_Wood_Material_0.geometry}
              material={materials.Wood_Material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/martial.gltf");
