/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Diego G. (https://sketchfab.com/empty_mirror)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/voxel-web-development-50ad959d6c6b4799806c45bfa46ca550
title: Voxel Web Development
*/

import { useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
export default function DevHome(props) {
  const [rotation, setRotation] = useState([0, 0, 0]);
  const { nodes, materials } = useGLTF("/devHome.gltf");

  useEffect(() => {
    const intervalId = setInterval(() => {
      setRotation((prevRotation) => [
        prevRotation[0] + 0.01,
        prevRotation[1] + 0.01,
        prevRotation[2] + 0.01,
      ]);
    }, 16.67);
    return () => clearInterval(intervalId);
  }, []);

  return (
    <group {...props} dispose={null} scale={1}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, rotation[1], 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.palette}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials["palette.001"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials["palette.002"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/devHome.gltf");
