/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: matousekfoto (https://sketchfab.com/matousekfoto)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-globe-98d2b04d46474bafb4250cc75dc583b3
title: Earth Globe 🌍
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Globe(props) {

  const { nodes, materials } = useGLTF("/globe.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-5.18, -20.68, 0]}
        rotation={[Math.PI / 2, -0.46, Math.PI]}
      >
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.meshNode_Material_u1_v2_0.geometry}
            material={materials.Material_u1_v2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.meshNode_Material_u2_v1_0.geometry}
            material={materials.Material_u2_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.meshNode_Material_u1_v1_0.geometry}
            material={materials.Material_u1_v1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/globe.glb");