/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mail-icon-b9133b28050d43aeb973aa0f08f86441
title: Mail Icon
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Mail(props) {
  const { nodes, materials } = useGLTF("/mail.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/mail.gltf");
